export const LOAD_CONTENT_REQUEST = 'LOAD_CONTENT_REQUEST'
export const LOAD_CONTENT_SUCCESS = 'LOAD_CONTENT_SUCCESS'
export const LOAD_CONTENT_FAILURE = 'LOAD_CONTENT_FAILURE'

export const CHANGE_PATH_FILE = 'CHANGE_PATH_FILE'
export const SET_PATH_FILE_ERROR = 'SET_PATH_FILE_ERROR'